# Generated by Django 5.0.8 on 2024-08-12 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('BASIC', 'Basic'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], max_length=20)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookclubapi.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookclubapi.subscription', verbose_name='Subscription Type'),
        ),
    ]
