# Generated by Django 5.0.8 on 2024-08-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapi', '0002_subscription_book_is_premium_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
