# Generated by Django 5.0.8 on 2024-08-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclubapi', '0003_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
